name: syncfusion_flutter_calendar
description: The Flutter Calendar widget has nine built-in configurable views that provide basic functionalities for scheduling and representing appointments/events efficiently.
version: 27.2.5
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_calendar

screenshots:
  - description: 'This screenshot shows the agenda view and recurrence view.'
    path: screenshots/flutter-calendar-agenda-view-recurrence-view.png
  - description: 'This screenshot shows the resource view and month cell customization.'
    path: screenshots/flutter-calendar-resource-view-month-cell-customization.png
  - description: 'This screenshot shows the load more feature in calendar.'
    path: screenshots/flutter-calendar-load-more.gif

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  timezone: 0.9.4
  syncfusion_flutter_core: ^27.2.5
  syncfusion_flutter_datepicker: ^27.2.5
  intl: '>=0.18.1 <0.20.0'

flutter:
  assets:
    - packages/timezone/data/latest_all.tzf
